### ISSUE TITLE
How to serve a whole (static) folder ?

### ISSUE THREAD

**Issue by orgicus** [transfluxus/SimpleHTTPServer#2]
I have basic web interface with several html/css/js files that I'm trying to serve using the SimpleHTTPServer library. I'm trying to recursively traverse the folder structure, but it doesn't seem to work. I get an error when trying to access files. These html/js files may reference files that are online.

Here is my basic attempt using the File I/O/DirectoryList Processing sample:

``` java
import java.util.Date;
import http.*;

SimpleHTTPServer server;

String path = "/path/to/my/http/folder";

void setup(){
  server = new SimpleHTTPServer(this);
  //server.serve("style.css");
  ArrayList<File> allFiles = listFilesRecursive(path);

  for (File f: allFiles) {
    println("Name: " + f.getName());
    println("Full path: " + f.getAbsolutePath());
    println("Is directory: " + f.isDirectory());
    println("Size: " + f.length());
    String lastModified = new Date(f.lastModified()).toString();
    println("Last Modified: " + lastModified);
    println("-----------------------");
    server.serve(f.getName(),f.getAbsolutePath());
  }
}
void draw(){

}
// This function returns all the files in a directory as an array of Strings  
String[] listFileNames(String dir) {
  File file = new File(dir);
  if (file.isDirectory()) {
    String names[] = file.list();
    return names;
  } else {
    // If it's not a directory
    return null;
  }
}

// This function returns all the files in a directory as an array of File objects
// This is useful if you want more info about the file
File[] listFiles(String dir) {
  File file = new File(dir);
  if (file.isDirectory()) {
    File[] files = file.listFiles();
    return files;
  } else {
    // If it's not a directory
    return null;
  }
}

// Function to get a list of all files in a directory and all subdirectories
ArrayList<File> listFilesRecursive(String dir) {
   ArrayList<File> fileList = new ArrayList<File>(); 
   recurseDir(fileList,dir);
   return fileList;
}

// Recursive function to traverse subdirectories
void recurseDir(ArrayList<File> a, String dir) {
  File file = new File(dir);
  if (file.isDirectory()) {
    // If you want to include directories in the list
    a.add(file);  
    File[] subfiles = file.listFiles();
    for (int i = 0; i < subfiles.length; i++) {
      // Call this function on all files in this directory
      recurseDir(a,subfiles[i].getAbsolutePath());
    }
  } else {
    a.add(file);
  }
}
```

Any hints/tips on how I could resolve this ? Would SimpleHTTPServer support what I'm attempting ?

Thank you,
George

**Comment by transfluxus** [comment]
Hi George,
it should work if the files are in the data folder. In the data folder only because the SimpleFileHandler doesn't support absolute paths at the moment, but only looks in the data folder. Absolute paths gonna come with an update I release latest this weekend. I'm gonna keep you posted on that

**Comment by transfluxus** [comment]
Hey can you try it again? Should work all fine now, with version 4
I actually added a function serveAll (multiple variants), which allows you to add directories.
See the doc for details.

**Comment by orgicus** [comment]
Thank you so much for your help.

I have tried it, but I get a lot warnings like these:

``` java
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
content type could not be derrived. Better use SimpleFileHandler(String fileName, String contentType)
```

I'm guessing those are problably .js/.css file it won't handle by default (as opposed to .html files) ?

**Comment by transfluxus** [comment]
Hey, 
actually js and css files should as html be derived.
But I'm gonna make this message more clear in the next release.

I changed the ServeAll example a bit, maybe you have a look:
https://www.dropbox.com/s/79wus24xpsfhae2/ServeFolder.zip?dl=0

**Comment by transfluxus** [comment]
any updates on that?

**Comment by orgicus** [comment]
Hi Ramin,

Apologies for the delay. I have tried a few different variations, but I can't seem to get my web folder running 100%. I couldn't figure out exactly why some scripts weren't working.
I'm basically trying to serve a Polymer based project and I used the [Polymer Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/?hl=en)

You can download my attempt [here](http://lifesine.eu/so/ServeFolder.zip).

Thank you very much for taking the time to look into this.
If you have hints/tips on what I could try on my own, I'd be more than glad to.
