### ISSUE TITLE
Can't update to version 1.4 from Processing IDE's "Libraries Manager" 

### ISSUE THREAD

**Issue by q2dg** [transfluxus/SimpleHTTPServer#3]
When I click on this library, it's installed version 1.3 (!?) and when I click on "Update to 1.4" button, it seems it will do it but it does nothing.
Thanks

EDIT: I use IDE 3.0.2

**Comment by transfluxus** [comment]
thanks for that post. I had the same Issue on Linux a while ago, but now when testing it again on a mac I have the same Issue. Gonna look into that.

**Comment by transfluxus** [comment]
Hi q2dg, there was wrong with the properties file.
should work now!

**Comment by q2dg** [comment]
Thanks to you!!
