### ISSUE TITLE
index.html can only be in data/

### ISSUE THREAD

**Issue by maxdee** [transfluxus/SimpleHTTPServer#4]
Library seems to work well with the exception that the `index.html` only works in `data/`. Serving an entire directory, for example `data/website/`, does not seem to work.
To be clear, I get a "404 Not Found
No context found for request".

**Comment by transfluxus** [comment]
Hi maxdee,
did you try the serveFolder example?
To serve an index on a different location you can try:

```
import http.*;
SimpleHTTPServer server;
void setup() {
    SimpleHTTPServer.useIndexHtml = false;
    server = new SimpleHTTPServer(this);
    server.serve("",sketchPath()+"/web/index.html");
}
```

**Comment by maxdee** [comment]
I had tried the serveAll example without success, but did not realize I needed to go to `localhost:8000/index.html` instead of `localhost:8000/`. All is good now! thanks for the library :)
I am using it to serve a web based gui for https://github.com/maxdee/alc_freeliner
